language: python

cache:
  directories:
    - $HOME/.cache/pip

# branches:
#  only:
#  - master
#  - "/^v.*$/"

# only test master and tagged releases on push
# # always test things that aren't pushes (like PRs)
if: type != push OR branch = master OR branch =~ /^v\d+\.\d+(\.\d+)?(-\S*)?$/

python:
  - "3.6"
  - "3.5"
  - "2.7"

script: tox

install: pip install tox-travis

jobs:
  include:
    - &check
      stage: check # do a pre-screen to make sure this is even worth testing
      python: '3.7'
      os: linux
      dist: xenial
    - &test
      stage: test
      os: osx
    - &integration
      stage: integration
      os: linux
      dist: xenial
      python: '3.7'
      install: sudo snap install ipfs
      services:
        - redis-server
        - docker
      script:
        - "/snap/bin/ipfs daemon --init --offline &>/dev/null &"
        - tox
stages:
  - check
  - test
  - integration
  - wheel
  - deploy
