name: asv benchmarks

on:
  push:
    branches: [latest]
  pull_request:
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: make latest branch available
      run: |
        git checkout latest
        git checkout -

    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9
        mamba-version: "*"
        miniforge-variant: Mambaforge
        use-mamba: true
        channels: conda-forge,bioconda,defaults
        channel-priority: true

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox-conda

    - name: Runs benchmarks against latest
      run: tox -e asv
